      common/vecsuv/ax(ifull),ay(ifull),az(ifull)
     .             ,bx(ifull),by(ifull),bz(ifull)
     .             ,cosa(ifull)
      dimension ax6(il,il,0:5),ay6(il,il,0:5),az6(il,il,0:5)
     .         ,bx6(il,il,0:5),by6(il,il,0:5),bz6(il,il,0:5)
      equivalence (ax6,ax),(ay6,ay),(az6,az)
     .           ,(bx6,bx),(by6,by),(bz6,bz)
